### ISSUE TITLE
Image button

### ISSUE THREAD

**Issue by jwerre** [surveyplanet/svelte_components#81]
Here's what the current image button looks like. It's essentially a checkbox or radio button.

```html
<label class="checkbox" for="5bedeb8ee41095464bc30405[1]" style="width: 220px"
  ><input
    name="5bedeb8ee41095464bc30405"
    id="5bedeb8ee41095464bc30405[1]"
    value="https://res.cloudinary.com/surveyplanet/image/upload/v1542318934/leryy5t0nlfiw1hmower.png"
    type="checkbox"
    required=""
  />
  <div class="checkbox-button"></div>
  <span class="label" id="label-5bedeb8ee41095464bc30405[1]"
    ><figure>
      <img
        src="https://res.cloudinary.com/surveyplanet/image/upload/b_white,c_pad,dpr_2.0,h_150,w_200/leryy5t0nlfiw1hmower"
        width="200"
        height="150"
        alt=""
      />
      <figcaption>Dylan</figcaption>
    </figure>
  </span>
</label>

```

```scss

$color_1: #800080;
$background-color_1: #fff;
$border-color_1: red;

.question.image-question {
	.question-form {
		ul {
			display: flex;
			flex-wrap: wrap;
			justify-content: center;
		}
	}
	.image-size-large {
		li {
			float: none;
			margin: half-gutter auto;
		}
		label {
			margin: 0 auto;
		}
	}
	.hide-captions {
		figcaption {
			display: none;
		}
	}
	li {
		float: left;
		margin: half-gutter;
		+ {
			li {
				margin: half-gutter;
			}
		}
	}
	label {
		display: block;
		background-color: $background-color_1;
		border-radius: default-radius;
		border: 1px solid slate-mid-light;
		padding: half-gutter;
		margin: 0;
		.radio-button {
			display: none;
		}
		.checkbox-button {
			display: none;
		}
		.label {
			padding: 0;
			figure {
				text-align: center;
			}
			figcaption {
				text-align: center;
				height: 20px;
				text-overflow: ellipsis;
				overflow: hidden;
			}
		}
	}
	label.checked {
		border-color: $border-color_1;
		box-shadow: overlay-shadow;
		figcaption {
			color: $color_1;
		}
	}
}


```

Notice that some of these styles have variables that don't exist so you'll need to replace them.
